version: '3'

networks:
  jupyterhub:
    external: false
    ipam:
      config:
        - subnet: 172.16.248.0/22
          gateway: 172.16.248.1
    name: ${JUPYTERHUB_NETWORK_NAME:-jupyterhub}

  proxy:
    external: true
    name: ${PROXY_NETWORK_NAME:-proxy}

services:
  jupyterhub:
    build:
      context: images/jupyterhub
      dockerfile: Dockerfile
      args:
        VERSION: ${JUPYTERHUB_VERSION:-latest}
      tags:
        # - my/jupyterhub:4.0
        - my/jupyterhub:${JUPYTERHUB_VERSION:-latest}
    image: my/jupyterhub:${JUPYTERHUB_VERSION:-latest}
    container_name: ${JUPYTERHUB_CONTAINER_NAME:-jupyterhub}
    hostname: ${JUPYTERHUB_HOSTNAME:-jupyterhub}
    restart: always
    networks:
      proxy:
        aliases:
          - ${JUPYTERHUB_HOSTNAME:-jupyterhub}
      jupyterhub:
        ipv4_address: ${JUPYTERHUB_IP:-172.16.248.254}
        aliases:
          - ${JUPYTERHUB_HOSTNAME:-jupyterhub}
    # ports:
    #   - ${JUPYTERHUB_HTTP_PORT:-15013}:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${JUPYTERHUB_DATA_DIR:-./data}:/data
      - ${JUPYTERHUB_CONFIG_DIR:-./config}:/etc/jupyterhub/:ro
      # - ${JUPYTERHUB_CONFIG_DIR:-./config}/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py:ro
      # - ${JUPYTERHUB_BASE_DIR:-.}/images/jupyterhub/src/config/MyOAuth.py:/config/MyOAuth.py:ro
      - ${JUPYTERHUB_BASE_DIR:-.}/images/jupyterhub/src/config:/config:ro
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py






