name: Publish Docker Image to GHCR and Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set environment variables
      run: echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV

    - name: Convert repository name to lowercase
      id: lower_repo_name
      run: echo "::set-output name=lower::$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ steps.lower_repo_name.outputs.lower }}:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Push the Docker image to GHCR
      run: docker push ghcr.io/${{ steps.lower_repo_name.outputs.lower }}:latest

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # - name: Push the Docker image to Docker Hub
    #   run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.lower_repo_name.outputs.lower }}:latest
